global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'infra-bot-webhook'  # 기본 수신자를 봇으로 설정
  routes:
  - match:
      alertname: Watchdog
    receiver: 'null' # Watchdog 무시
  - match:
      alertname: InfoInhibitor
    receiver: 'null' # InfoInhibitor 무시

receivers:
- name: 'null'
- name: 'infra-bot-webhook'
  webhook_configs:
  - url: 'http://infra-bot-service.default.svc.cluster.local/alert'
    send_resolved: true
