apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: portforge-api
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:023490709500:certificate/a3ba126a-a642-41a0-b83a-f26ba202e6ff
    alb.ingress.kubernetes.io/subnets: subnet-0e6a90b53897142fc, subnet-0e076e9182ac358ad
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    # AI 문제 생성은 시간이 오래 걸리므로 타임아웃 5분으로 설정
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 8003
